name: dmcgb
channels:
  - defaults
dependencies:
  - python=3.6.12
  - cudatoolkit=10.2.89
  - pytorch=1.10.1
  - torchvision=0.11.2
  - numpy=1.19.2
  - pip
  - pyparsing
  - pip:
    - gym==0.19.0
    - imageio==2.15.0
    - imageio-ffmpeg==0.4.9
    - opencv-contrib-python==3.4.1.15
    - absl-py
    - pillow
    - scipy
    - tensorboard
    - termcolor
    - torchgeometry
    - tqdm
    - xmltodict
    - matplotlib
    - kornia
    - captum
